# Generated by Django 3.0.8 on 2020-07-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeissSchwarz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='カード名')),
                ('num', models.CharField(blank=True, max_length=30, verbose_name='カード番号')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='収録弾')),
                ('side', models.CharField(blank=True, choices=[('W', 'W'), ('S', 'S')], max_length=2, verbose_name='サイド')),
                ('kind', models.CharField(blank=True, choices=[('キャラ', 'キャラ'), ('イベント', 'イベント'), ('クライマックス', 'クライマックス')], max_length=20, verbose_name='種類')),
                ('level', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=2, verbose_name='レベル')),
                ('color', models.CharField(blank=True, choices=[('黄', '黄'), ('緑', '緑'), ('赤', '赤'), ('青', '青')], max_length=10, verbose_name='色')),
                ('power', models.CharField(blank=True, max_length=10, verbose_name='パワー')),
                ('soul', models.CharField(blank=True, choices=[('-', '-'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=2, verbose_name='ソウル')),
                ('cost', models.CharField(blank=True, max_length=2, verbose_name='コスト')),
                ('rarity', models.CharField(blank=True, max_length=30, verbose_name='レアリティ')),
                ('trigger', models.CharField(blank=True, max_length=30, verbose_name='トリガー')),
                ('identity', models.CharField(blank=True, max_length=50, verbose_name='特徴')),
                ('flavor', models.TextField(blank=True, max_length=255, verbose_name='フレーバー')),
                ('text', models.TextField(blank=True, max_length=500, verbose_name='テキスト')),
            ],
        ),
        migrations.CreateModel(
            name='Yugioh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='カード名')),
                ('reading', models.CharField(blank=True, max_length=100, verbose_name='ルビ')),
                ('element', models.CharField(blank=True, max_length=2, verbose_name='属性')),
                ('level', models.IntegerField(blank=True, verbose_name='レベル')),
                ('species', models.CharField(blank=True, max_length=50, verbose_name='種族')),
                ('attack', models.IntegerField(blank=True, verbose_name='攻撃力')),
                ('defence', models.IntegerField(blank=True, verbose_name='防御力')),
                ('text', models.TextField(blank=True, max_length=500, verbose_name='テキスト')),
            ],
        ),
    ]
