# Generated by Django 3.0.8 on 2020-08-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weissschwarz',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='画像'),
        ),
        migrations.AddField(
            model_name='yugioh',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='画像'),
        ),
    ]
