# Generated by Django 3.0.8 on 2020-08-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20200802_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weissschwarz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='yugioh',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像'),
        ),
    ]
