# Generated by Django 3.0.8 on 2020-07-11 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('khpost', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='マイデッキ', max_length=100, verbose_name='デッキタイトル')),
                ('kind', models.IntegerField(choices=[(0, 'デッキ'), (1, 'メモ')], default=0, verbose_name='種類')),
                ('progress', models.IntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4'), (4, '5')], default=0, verbose_name='完成度')),
                ('label_first', models.CharField(blank=True, default='メインデッキ', max_length=20, verbose_name='ラベル１')),
                ('label_second', models.CharField(blank=True, default='エクストラデッキ', max_length=20, verbose_name='ラベル２')),
                ('label_third', models.CharField(blank=True, default='サイドデッキ', max_length=20, verbose_name='ラベル３')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='説明')),
                ('is_public', models.IntegerField(choices=[(0, '非公開'), (1, '公開')], default=0, verbose_name='公開設定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='khpost.GameTitleModel', verbose_name='ゲームタイトル')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='デッキ所持者')),
            ],
        ),
        migrations.CreateModel(
            name='YugiohDeckContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_card', models.IntegerField(default=1, verbose_name='枚数')),
                ('label', models.IntegerField(choices=[(0, 'ラベル１'), (1, 'ラベル２'), (2, 'ラベル３')], default=0, verbose_name='ラベル')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.MyDeck')),
                ('yugioh', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='storage.Yugioh', verbose_name='遊戯王')),
            ],
        ),
        migrations.CreateModel(
            name='WeissSchwarzDeckContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_card', models.IntegerField(default=1, verbose_name='枚数')),
                ('label', models.IntegerField(choices=[(0, 'ラベル１'), (1, 'ラベル２'), (2, 'ラベル３')], default=0, verbose_name='ラベル')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.MyDeck')),
                ('weiss_schwarz', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='storage.WeissSchwarz', verbose_name='ヴァイスシュヴァルツ')),
            ],
        ),
    ]
