# Generated by Django 3.0.4 on 2020-05-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weissschwarz',
            name='flavor',
            field=models.TextField(blank=True, max_length=255, verbose_name='フレーバー'),
        ),
        migrations.AlterField(
            model_name='weissschwarz',
            name='text',
            field=models.TextField(blank=True, max_length=500, verbose_name='テキスト'),
        ),
    ]
