# Generated by Django 3.0.4 on 2020-04-26 01:28

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('khpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='bookmarkmodel',
            name='bookmark_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ブックマークしたユーザー'),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='like_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='いいねしたユーザー'),
        ),
    ]
