# Generated by Django 3.0.4 on 2020-05-25 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khpost', '0002_auto_20200524_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametitlemodel',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='ゲームタイトル名'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=150, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='タグ名'),
        ),
    ]
