# Generated by Django 3.0.4 on 2020-04-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khpost', '0002_auto_20200426_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='is_public',
            field=models.IntegerField(choices=[(0, '非公開'), (1, '公開')], default=0, verbose_name='公開設定'),
        ),
    ]
