# Generated by Django 3.0.4 on 2020-04-22 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hiroba', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hiroba',
            options={'verbose_name_plural': '記事モデル'},
        ),
        migrations.AddField(
            model_name='hiroba',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='アドいいね'),
        ),
    ]
